version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
      pre_create_environment:
        - rm -rf docs/source/_build
      post_build:
        - echo "Command run at 'post_build' step"
        - echo `date`

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
        
