# File: .readthedocs.yaml

version: 2

build:
  tools:
    python: "3.7.6"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - furo
  system_packages: true